name: getbloc
description: Create GetX Controllers with Events and/or States, instead using Provider as the bloc library uses, GetBloc uses GetX.
version: 1.2.0
homepage: https://github.com/Eronildo/getbloc/tree/main/packages/getbloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.2.4
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  pedantic: ^1.11.1
  rxdart: ^0.27.1
