name: getbloc_test
description: A testing library which makes it easy to test controllers. Built to be used with the GetBloc package.
version: 1.0.0
homepage: https://github.com/Eronildo/getbloc/tree/master/packages/getbloc_test

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getbloc: ^1.0.0
  meta: ^1.3.0
  mocktail: ^0.1.4
  test: ^1.16.0

dev_dependencies:
  pedantic: ^1.11.0
  rxdart: ^0.27.1
