name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  equatable: ^2.0.3
  getbloc: ^1.2.0
  getbloc_test:
    path: ../

dev_dependencies:
  effective_dart: ^1.3.2

flutter:
  uses-material-design: true
